// Authored encounters: permanent identities shared by combat, rumour pins and weapon finishes.
const boss=(id,name,location,x,z,shape,skin,xp,cash,attacks,hint,rumour)=>({id,name,location,x,z,shape,skin,xp,cash,attacks,hint,rumour,radius:42,discoverR:72,hp:shape==='tree'?1450:1200});
const skin=(id,name,base,accent,pattern)=>({id,name,colors:{base,accent,metal:0x515563},pattern});
export const BOSSES=Object.freeze([
 boss('blacktide','Mother of Tides','Brine Lock',-2614,-286,'sea',skin('blacktide','Drowned Pearl',0x19373d,0x97ecce,'scales'),650,360,['undertow','tentacles','spit'],'The pearl inside the open mouth is soft. Broken pressure tanks make her surface.','West of the drowned light, the lock gates breathe. The boats come back inside out.'),
 boss('rootmother','The Orchard Mother','Widow\'s Orchard',-1362,2156,'tree',skin('rootmother','Heartwood',0x392826,0xd78574,'veins'),650,340,['roots','sweep','roots'],'Her heart opens after the roots strike. Rupture the amber sap bladders.','There is an orchard south-west of the chapel. Nothing grows on it except teeth.'),
 boss('bellwether','The Bellwether','Bellfounder\'s Cut',1689,-2120,'bell',skin('bellwether','Mourning Brass',0x4b3b2b,0xdcc28a,'rings'),620,330,['ring','charge','ring'],'Jump the travelling shockwave. The bell-mouth opens after it rings.','Past Jackfield, a bell walks on hands. Stand still and you will hear your own funeral.'),
 boss('choir','The Unfinished Choir','Choir Silos',611,2804,'choir',skin('choir','Choirbone',0x3c303c,0xe3c8b7,'ribs'),650,350,['cross','spit','cross'],'The singing throats flare before their lines strike. Break a resonator to silence them.','South of the county, the grain silos sing. Some of the voices are still asking to be let out.'),
 boss('furnace','The Kiln Saint','Charcoal Works',2578,-523,'furnace',skin('furnace','Kilnfire',0x231d1a,0xf69954,'cracks'),660,370,['vents','slam','vents'],'Stay between the burning seams. The furnace door opens to cool after each blast.','The old charcoal works burn without wood. We stopped counting the shapes in the smoke.'),
 boss('lantern','The Lantern Eater','Last Light Viaduct',2646,1305,'lantern',skin('lantern','Stolen Light',0x24263c,0xd6d0ff,'stars'),640,350,['charge','cross','charge'],'Its lure brightens before the rush. Step aside; the swallowed lamp stays exposed afterward.','There is a light under the south-east viaduct that follows you. Do not follow it back.'),
 boss('mire','The Mire Bride','Wading Chapel',-2755,1261,'mire',skin('mire','Bog Opal',0x283b33,0xb4cf95,'scales'),620,330,['spit','roots','undertow'],'Her veil parts after she spits. Pop the swollen gas sacs for a longer opening.','At the western wading chapel, something wears the wedding clothes we left for the dead.'),
 boss('moth','The Moonmolt','Lunar Conservatory',512,-2905,'moth',skin('moth','Moonwing',0x323343,0xb5cfe8,'wings'),650,350,['cross','ring','spit'],'The throat shines while the wings rest. Watch the pale dust lines before they ignite.','Beyond the northern quarry, the glasshouse is wrapped in a wing. It has not finished unfolding.'),
 boss('antler','The Antlered Engine','Stag Crossing',-811,-2418,'antler',skin('antler','Winter Crown',0x303534,0xd2c7a5,'antlers'),650,340,['charge','sweep','charge'],'The charge commits to a line. Draw it past a signal drum and break the drum.','At the old northern crossing the railway still moves. It has learned to walk through the trees.'),
 boss('underkeep','The Kept','Beneath the Holdfast',3500,3500,'crypt',skin('underkeep','Sepulchre',0x313344,0xd9cee9,'ribs'),750,450,['hands','slam','cross'],'Hands mark the floor before they close. The heart behind the ribs opens after the grasp.','Behind the east houses, there is a sealed stair. We keep leaving food. The bowls come back clean.'),
]);
export const BOSS_BY_ID=Object.freeze(Object.fromEntries(BOSSES.map(b=>[b.id,b])));
export const CRYPT={x:3500,z:3500,entryX:3500,entryZ:3537,hatchX:45,hatchZ:-43};
export function bossMapPoint(b){return b.id==='underkeep'?{x:0,z:0}:{x:b.x,z:b.z};}
export function bossClearance(x,z,padding=0){return BOSSES.some(b=>Math.hypot(x-b.x,z-b.z)<b.radius+padding);}
