// Physical records transcribed from the supplied Lore Bible. The hidden account is never printed.
export const SITE_RECORDS = Object.freeze([
  {
    "id": "site:filling-station",
    "siteId": "filling-station",
    "title": "LAMINATED COUNTY NOTICE",
    "text": "MERIDIAN COUNTY EMERGENCY EVACUATION · ASSEMBLY POINT 3 · REMAIN AT THIS LOCATION · TRANSPORT DEPARTS AT FIRST LIGHT\n\nfirst light tuesday\nfirst light this week\nfirst light\nlight",
    "x": -14.8,
    "y": 1.7,
    "z": -3.17,
    "yaw": 3.14159,
    "mount": "wall"
  },
  {
    "id": "site:blackthorn-manor",
    "siteId": "blackthorn-manor",
    "title": "CARD ON THE DINING TABLE",
    "text": "WE SHALL RISE TO MEET IT — J.B. · You first, Grandfather.",
    "x": 14,
    "y": 3.974,
    "z": 11,
    "yaw": 0,
    "mount": "surface",
    "w": 0.45,
    "h": 0.55
  },
  {
    "id": "site:avery-house",
    "siteId": "avery-house",
    "title": "NOTE IN THE CHILD'S ROOM",
    "text": "Dad is outside watching so nothing gets us. He said he can see us from there. I waved. I dont think he saw.",
    "x": -26.5,
    "y": 8.4,
    "z": -12.5,
    "yaw": 0,
    "mount": "desk",
    "floor": 7.4
  },
  {
    "id": "site:weeping-mine",
    "siteId": "weeping-mine",
    "title": "UNDER THE DANGER · NO ENTRY PLACARD",
    "text": "IT'S WARM DOWN HERE\n\nthat's not a good thing",
    "x": 7.6,
    "y": 1.7,
    "z": -7.3,
    "yaw": 0,
    "mount": "board",
    "ground": true,
    "floor": 0
  },
  {
    "id": "site:holdfast",
    "siteId": "holdfast",
    "title": "CARVED INTO THE INSIDE OF THE GATE",
    "text": "BELLS FOR THE RETURNING · BREAD FOR THE STAYING · SILENCE FOR THE STAIR",
    "x": 2,
    "y": 1.6,
    "z": 63.78,
    "yaw": 3.14159,
    "mount": "wall"
  },
  {
    "id": "site:the-toll",
    "siteId": "the-toll",
    "title": "CLIPBOARD AT THE CASHIER'S WINDOW",
    "text": "MERIDIAN CO. SHERIFF · EVACUATION CONTROL POINT 1 · HOLD UNTIL RELIEVED · vehicles processed: 2,211 · vehicles returned: 0 · relief ETA: ______",
    "x": 7,
    "y": 1.12,
    "z": 6,
    "yaw": 0,
    "mount": "desk",
    "ground": true,
    "floor": 0
  },
  {
    "id": "site:relay",
    "siteId": "relay",
    "title": "DELL'S LOG",
    "text": "Heard Springfield again. 2:14 in the afternoon their time. Lawn furniture, half off. Sunny.\n\nRan the numbers. If it's afternoon there and the same night here, it's still the same night here. It's been the same night here the whole time. We're the ones stuck.\n\nNot telling Vera. She counts days. Let her have them.",
    "x": -14.6,
    "y": 0.925,
    "z": 2.025,
    "yaw": 0,
    "mount": "surface",
    "ground": true,
    "w": 0.45,
    "h": 0.25
  },
  {
    "id": "site:cathedral",
    "siteId": "cathedral",
    "title": "ORDER OF SERVICE",
    "text": "THE VIGIL OF LIGHT · The church is in darkness. The people wait. The new fire is kindled outside the west door and carried in, and the deacon sings: THE LIGHT OF CHRIST. The people answer: THANKS BE TO GOD. Sunrise Mass to follow at 6:31.\n\nSix years of pencil ticks beside “The people wait.”",
    "x": 2.5,
    "y": 1.02,
    "z": 13,
    "yaw": 0,
    "mount": "desk",
    "ground": true,
    "floor": 0
  },
  {
    "id": "site:chapel",
    "siteId": "chapel",
    "title": "CHALK ON THE WARD WALL BESIDE THE SHADOW",
    "text": "her name was Cass · she saw it · it was warm · she said it was warm",
    "x": -14.5,
    "y": 4.43,
    "z": -5.125,
    "yaw": 0,
    "mount": "wall"
  },
  {
    "id": "site:gallowsfen",
    "siteId": "gallowsfen",
    "title": "SEXTON'S SLATE",
    "text": "WAKES HELD · 15 · BURIALS · 0 · GROUND · WET · LAMP · UP",
    "x": 8.3,
    "y": 1.6,
    "z": -11.6,
    "yaw": 0,
    "mount": "board",
    "ground": true,
    "floor": 0
  },
  {
    "id": "site:drowned-light",
    "siteId": "drowned-light",
    "title": "LIGHTHOUSE LOG",
    "text": "Night 4. Nine boats out, 1:10. Lamps visible. 1:20 lamps visible. 1:30 eight lamps. 1:40 five. 1:50 one. 1:59 —\n\nNight 4. Nine boats out, 1:10. Lamps visible. 1:20 lamps visible. 1:30 eight lamps. 1:40 five. 1:50 one. 1:59 —",
    "x": 1.8,
    "y": 37.72,
    "z": 1.5,
    "yaw": 0,
    "mount": "desk",
    "floor": 36.7
  },
  {
    "id": "site:hollow-mill",
    "siteId": "hollow-mill",
    "title": "CHALK TALLY ON THE GEAR-RING POST",
    "text": "stopped counting turns · Wendell says count nights instead · stopped counting nights",
    "x": 2.9,
    "y": 1.5,
    "z": 3.2,
    "yaw": 0,
    "mount": "board",
    "ground": true,
    "floor": 0
  },
  {
    "id": "site:garden-of-rest",
    "siteId": "garden-of-rest",
    "title": "SEXTON'S NOTICE",
    "text": "NEW BURIALS FACE WEST · NO EXCEPTIONS · I DON'T CARE WHAT THE STONE SAYS · — H. Ostrander, Sexton",
    "x": 11.9,
    "y": 1.6,
    "z": 13.38,
    "yaw": 3.14159,
    "mount": "wall"
  },
  {
    "id": "site:bell-tower",
    "siteId": "bell-tower",
    "title": "ON THE RINGING FLOOR",
    "text": "Rang the one o'clock. Waited. Clock says one again. Rang it again in case. Waiting for six. Will ring at six. — T.\n\nstill one.",
    "x": -1.3,
    "y": 20.05,
    "z": 1.5,
    "yaw": 0,
    "mount": "desk",
    "floor": 19
  },
  {
    "id": "site:jackfield",
    "siteId": "jackfield",
    "title": "FEED-STORE CALENDAR IN THE WORKSHOP",
    "text": "Halloween · clocks back tonight · EXTRA HOUR OF SLEEP",
    "x": -20.5,
    "y": 1.65,
    "z": -4.85,
    "yaw": 0,
    "mount": "board",
    "ground": true,
    "floor": 0
  },
  {
    "id": "site:standing-stones",
    "siteId": "standing-stones",
    "title": "NOTHING WRITTEN. A COUNTY HISTORICAL MARKER AT THE ROAD",
    "text": "THE STANDING STONES · Ceremonial ring, origin unknown, est. 3,000 years. Local tradition held that a fire be kept here on the last night of October \"until the sun is rung up.\" The custom lapsed in 1922.",
    "x": 8,
    "y": 1.6,
    "z": 15,
    "yaw": 0,
    "mount": "board",
    "ground": true,
    "floor": 0
  },
  {
    "id": "site:great-tree",
    "siteId": "great-tree",
    "title": "LOOKOUT LOGBOOK",
    "text": "Oct 31. Sunset 5:41. Clear. Drew it. (sketch) \n\nNov 1. No sunrise. The lighthouse and the church, same as always. Nothing else.\n\nNight 30. Eleven fires, not counting the two that were always there: the lock, the orchard, Kohl's cut, the silos, the works, the viaduct, the wedding in the fen, the conservatory, the crossing, the keep, and the lights on the backhoe in Jackfield's west field.\n\n— eleven. — eleven. — ten (the field). — nine (the lock). — nine. — eight (the silos went quiet, still lit, not counting it) —\n\nthree.",
    "x": 3.35,
    "y": 13.91,
    "z": 2.8,
    "yaw": 0,
    "mount": "desk",
    "floor": 12.9
  },
  {
    "id": "site:black-rib",
    "siteId": "black-rib",
    "title": "CARVED INTO THE FIRST PORTAL",
    "text": "WHAT SWALLOWED IT WAS OPENED HERE\n\nOPEN IT AGAIN",
    "x": 2.4,
    "y": 1.8,
    "z": 12.3,
    "yaw": 0,
    "mount": "board",
    "ground": true,
    "floor": 0
  },
  {
    "id": "site:mourning-glasshouse",
    "siteId": "mourning-glasshouse",
    "title": "HAND-PAINTED SIGN AT THE ROAD",
    "text": "MO(U)RNING GLASS NURSERY · Annuals · Perennials · Something For Every Season",
    "x": 4.6,
    "y": 1.5,
    "z": -38,
    "yaw": 0,
    "mount": "board",
    "ground": true,
    "floor": 0
  },
  {
    "id": "site:choir-vault",
    "siteId": "choir-vault",
    "title": "CHOIR FOLDER ON THE WALKWAY",
    "text": "VIGIL OF LIGHT · 31 voices · Hold the final verse until the sun is visible from the walkway. — D.Q.",
    "x": 16,
    "y": 6.21,
    "z": -32.6,
    "yaw": 0,
    "mount": "desk",
    "floor": 5.2
  },
  {
    "id": "site:red-quarry",
    "siteId": "red-quarry",
    "title": "WORK ORDER CLIPPED TO THE CRANE CAB",
    "text": "BLOCK 1 · RED · 9m x 4m x 3m · INSCRIPTION: TO FOLLOW",
    "x": 25.4,
    "y": 8.21,
    "z": -37.3,
    "yaw": 0,
    "mount": "desk",
    "floor": 7.2
  }
]);
