import * as THREE from 'three';
import {BRANCHES,NODES} from '../progression/nodes.js';
import {FINISHES,FINISH_BY_ID,finishMaterial,setMaterialFinish} from '../weapons/finishes.js';

const el=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
const button=(text,fn,cls='')=>{const b=el('button',cls,text);b.type='button';b.addEventListener('click',fn);return b;};
const HEX=n=>'#'+n.toString(16).padStart(6,'0');
const WEAPON_NAMES={bolt:'Bolt rifle',carbine:'Carbine',shotgun:'Shotgun',revolver:'Revolver'};
const BRANCH_DETAIL={legs:'Keep moving. Recover from a fall, cross open ground, escape a closing distance.',hands:'Make every opening count. Keep the gun working when a fight turns ugly.',lamp:'Turn what you carry into something the dark has to answer.',quiet:'Choose when a fight begins. Leave nothing behind for it to follow.',blood:'Survive the moment that should have finished you.'};
const ICONS={legs:'↟',hands:'⌁',lamp:'☼',quiet:'◌',blood:'◈'};

const CSS=`
#curfew-pause{padding:0;background:radial-gradient(ellipse at 78% 12%,#243345a8,transparent 55%),linear-gradient(120deg,#05090fed,#090e16eb);backdrop-filter:blur(12px);color:#d8e1e9;font-family:Inter,Segoe UI,Arial,sans-serif}
#curfew-pause::before{display:none}#curfew-pause .card{width:min(1420px,94vw);padding:32px 0 22px;margin:auto;box-sizing:border-box}
#curfew-pause [hidden]{display:none!important}#curfew-pause button{font:inherit;color:inherit}#curfew-pause button:focus-visible{outline:2px solid #e1cca6;outline-offset:4px}#curfew-pause button:disabled{cursor:default}
#curfew-pause .menu-head{display:flex;align-items:center;justify-content:space-between;gap:25px;border-bottom:1px solid #64718555;padding-bottom:17px;margin-bottom:28px}
#curfew-pause .menu-brand{font:10px/1.5 ui-monospace,Consolas,monospace;letter-spacing:.23em;color:#99aabb;text-transform:uppercase}#curfew-pause h1{font-size:29px;letter-spacing:.025em;font-weight:400;margin:7px 0 0}
#curfew-pause .menu-nav{display:flex;gap:5px;align-items:center;flex-wrap:wrap}#curfew-pause .menu-nav button{border:0;background:transparent;color:#9cabbb;padding:12px 16px;font-size:13px;border-bottom:2px solid transparent;cursor:pointer}
#curfew-pause .menu-nav button[aria-current=page]{color:#f2e1bd;border-color:#dbc69c}#curfew-pause .menu-nav button:hover{background:#869ab411;color:#edf1f5}
#curfew-pause .menu-page{min-height:min(590px,68vh)}#curfew-pause .menu-footer{border-top:1px solid #64718544;margin-top:24px;padding-top:15px;display:flex;justify-content:space-between;color:#7f91a4;font:11px/1.5 ui-monospace,Consolas,monospace}
#curfew-pause .menu-footer button{border:0;background:transparent;cursor:pointer;color:#ccd6df}#curfew-pause kbd{font:10px ui-monospace,Consolas,monospace;border:1px solid #7e8f9e66;border-radius:3px;padding:3px 6px;color:#b8c4d0;margin-right:9px}
#curfew-pause .pause-home{display:grid;grid-template-columns:1.2fr 1fr;gap:70px;align-items:center;padding:30px 7% 40px;box-sizing:border-box}
#curfew-pause .home-moon{width:166px;height:166px;border:1px solid #ccd5df80;border-radius:50%;box-shadow:inset -22px 0 24px #a7bdd32b,0 0 85px #9fb8d411;margin:0 0 30px;position:relative}#curfew-pause .home-moon:after{content:'';position:absolute;inset:11px 30px 11px 10px;border-radius:50%;border-right:2px solid #b6c6d8aa;transform:rotate(-24deg)}
#curfew-pause .home-name{font-size:clamp(28px,3.4vw,49px);font-weight:300;line-height:1.1;letter-spacing:.015em;max-width:400px;margin:0 0 22px}#curfew-pause .home-status{font:12px/1.7 ui-monospace,Consolas,monospace;color:#a5b5c4}
#curfew-pause .home-choices{display:grid;gap:10px}#curfew-pause .home-choice{display:flex;align-items:center;text-align:left;justify-content:space-between;border:1px solid #7283994d;background:linear-gradient(100deg,#2c3b4c33,#2937440a);padding:20px 23px;cursor:pointer;transition:background .16s,border-color .16s,transform .16s}
#curfew-pause .home-choice:hover{border-color:#c8bb99aa;background:#586a7f2e;transform:translateX(4px)}#curfew-pause .home-choice strong{display:block;font-size:20px;font-weight:400}#curfew-pause .home-choice small{display:block;margin-top:6px;color:#93a6b6;font-size:12px}#curfew-pause .home-choice:first-child{border-color:#c3b29077;background:#b5a07412}
#curfew-pause .perks-layout{display:grid;grid-template-columns:minmax(0,1fr) 285px;gap:28px}#curfew-pause .tree{padding:0;background:transparent;border:0;min-width:0}#curfew-pause .lvl{font-size:18px;margin:0 0 16px}#curfew-pause .lvl .pts{color:#f2d69e;font-size:12px}#curfew-pause .xp{margin-bottom:10px}#curfew-pause .carry-note{margin-bottom:16px}
#curfew-pause .perk-branches{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:15px}#curfew-pause .br{display:flex;flex-direction:column;gap:15px;margin:0;min-width:0}#curfew-pause .br:after{display:none}#curfew-pause .bn{height:44px;text-align:center;font-size:12px;letter-spacing:.16em;display:flex;align-items:center;justify-content:center;border-bottom:1px solid color-mix(in srgb,var(--accent) 28%,transparent)}#curfew-pause .bn:before{display:none}
#curfew-pause .nd{height:91px;min-height:91px;padding:13px 10px 10px 24px;background:linear-gradient(145deg,#2b394822,#0c131b66);text-align:left;transition:border-color .16s,background .16s,transform .16s;cursor:pointer;border:1px solid #57677666}
#curfew-pause .nd .cn{font-size:12px;line-height:1.4;display:block}#curfew-pause .nd .cn>span:first-child{display:block;min-height:32px}#curfew-pause .nd .cm{margin-top:6px;justify-content:space-between}#curfew-pause .nd .ct{font-size:9px;color:var(--accent)}#curfew-pause .nd .cc{font-size:8px;letter-spacing:.06em}#curfew-pause .nd .cl{display:none}
#curfew-pause .nd+.nd:before{left:50%;top:-16px;width:1px;height:14px;background:#6a7c9166}#curfew-pause .nd.own+.nd:before{background:var(--accent)}#curfew-pause .nd.lock{opacity:.55;filter:none}#curfew-pause .nd.poor{opacity:.76}#curfew-pause .nd .dot{top:17px;left:9px;width:7px;height:7px}#curfew-pause .nd.lock .dot{top:18px;left:10px;width:5px;height:5px}
#curfew-pause .nd[data-selected=true]{border-color:var(--accent);background:color-mix(in srgb,var(--accent) 11%,#101925);box-shadow:0 0 26px color-mix(in srgb,var(--accent) 8%,transparent)}
#curfew-pause .perk-detail{border-left:1px solid #63718855;padding:25px 0 16px 25px;align-self:stretch;display:flex;flex-direction:column}#curfew-pause .perk-emblem{font:72px/1 Georgia,serif;color:var(--accent);height:95px;opacity:.85}#curfew-pause .detail-eyebrow{text-transform:uppercase;font:10px/1.6 ui-monospace,Consolas,monospace;letter-spacing:.18em;color:var(--accent)}#curfew-pause .perk-detail h2{font-size:27px;font-weight:400;line-height:1.15;margin:14px 0 18px}#curfew-pause .perk-description{font-size:16px;line-height:1.65;color:#d1dce3}#curfew-pause .perk-context{font-size:12px;line-height:1.8;color:#8396a7;margin:20px 0}
#curfew-pause .perk-action{padding-top:24px;margin-top:auto}#curfew-pause .primary-action{width:100%;padding:15px;border:1px solid #d5c095aa;background:#d5c09516;color:#ebd8b5;cursor:pointer;font-size:14px}#curfew-pause .primary-action:hover:enabled{background:#d5c0952a}#curfew-pause .primary-action:disabled{background:#7e8c9811;color:#8797a5;border-color:#7e8c9844}#curfew-pause .detail-requirement{min-height:31px;margin:12px 0 0;color:#a6b4bf;font-size:11px;line-height:1.5}
#curfew-pause .map-page{display:grid;grid-template-columns:minmax(0,1fr) 285px;gap:28px;align-items:start}#curfew-pause .map-wrap{max-width:none}#curfew-pause .map{width:min(68vh,100%);max-width:760px;margin:0 auto;background:#050a1077;border:1px solid #64718533}#curfew-pause .map-journal{border-left:1px solid #64718544;padding-left:23px;max-height:65vh;overflow:auto}#curfew-pause .map-journal h2{font-size:16px;font-weight:400;margin:5px 0 20px}#curfew-pause .map-pin{display:block;width:100%;border:0;border-bottom:1px solid #63718433;background:transparent;text-align:left;padding:13px 0;cursor:pointer}#curfew-pause .map-pin strong{display:block;font-size:13px;font-weight:400}#curfew-pause .map-pin small{display:block;font:10px/1.5 ui-monospace,Consolas,monospace;color:#bea780;margin-top:5px}#curfew-pause .map-pin[data-state=cleared] small{color:#96c9ad}#curfew-pause .map-journal p{font-size:13px;line-height:1.8;color:#879baa}
#curfew-pause .controls-page{max-width:1000px;margin:auto}#curfew-pause .controls-page h2{font-size:21px;font-weight:400;margin:0 0 10px}#curfew-pause .controls-page p{color:#92a4b3;font-size:13px;margin:0 0 28px}#curfew-pause dl{grid-template-columns:repeat(2,minmax(0,1fr));gap:16px 50px}#curfew-pause .pair{padding:12px 0;border-bottom:1px solid #67778d44}#curfew-pause dt{font-size:11px;opacity:.75}#curfew-pause dd{font-size:13px}
#curfew-pause .weapons-page{display:grid;grid-template-columns:340px minmax(0,1fr);gap:34px}#curfew-pause .finish-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;align-content:start;max-height:66vh;overflow:auto;padding:4px}#curfew-pause .finish-tile{position:relative;text-align:left;min-height:89px;padding:13px 11px;border:1px solid #63758b55;background:linear-gradient(140deg,var(--finish) -120%,#121c29 65%);cursor:pointer}#curfew-pause .finish-tile strong{display:block;font-size:12px;font-weight:500;margin-top:17px}#curfew-pause .finish-tile small{display:block;font-size:9px;line-height:1.5;color:#90a1b2;margin-top:6px}#curfew-pause .finish-tile:before{content:'';position:absolute;top:12px;left:12px;width:26px;height:3px;background:var(--accent);box-shadow:8px 0 14px var(--accent)}#curfew-pause .finish-tile[data-selected=true]{border-color:var(--accent)}#curfew-pause .finish-tile[data-locked=true]{opacity:.56}#curfew-pause .finish-tile[data-equipped=true]:after{content:'✓';position:absolute;right:10px;top:8px;color:#e4d3ae}
#curfew-pause .finish-stage{min-width:0}#curfew-pause .weapon-tabs{display:flex;gap:8px;flex-wrap:wrap}#curfew-pause .weapon-tabs button{border:1px solid #66768a44;background:transparent;padding:9px 13px;font-size:11px;cursor:pointer}#curfew-pause .weapon-tabs button[aria-pressed=true]{border-color:#bda97e;color:#eddcba}#curfew-pause .weapon-preview{height:min(39vh,390px);min-height:210px;position:relative;background:radial-gradient(ellipse,#34425744,transparent 65%);cursor:grab}#curfew-pause .weapon-preview canvas{display:block;width:100%;height:100%}#curfew-pause .preview-hint{font:10px/1.7 ui-monospace,Consolas,monospace;color:#8194a8;margin:0 0 23px}#curfew-pause .finish-description{display:grid;grid-template-columns:1fr 180px;gap:25px;border-top:1px solid #63718855;padding-top:22px}#curfew-pause .finish-description h2{font-size:28px;font-weight:400;margin:0 0 10px}#curfew-pause .finish-description p{font-size:12px;line-height:1.7;color:#9bafbf;margin:0}
@media(max-width:1100px){#curfew-pause .perks-layout{grid-template-columns:minmax(0,1fr) 230px;gap:18px}#curfew-pause .perk-branches{gap:9px}#curfew-pause .nd{height:97px;padding-left:21px}#curfew-pause .perk-detail{padding-left:18px}#curfew-pause .menu-nav button{padding:10px}#curfew-pause .pause-home{gap:30px;padding:20px 3%}#curfew-pause .weapons-page{grid-template-columns:290px 1fr}}
@media(max-height:760px){#curfew-pause .card{padding:20px 0 15px}#curfew-pause .menu-head{margin-bottom:18px;padding-bottom:12px}#curfew-pause .menu-page{min-height:0}#curfew-pause .nd{height:73px;min-height:73px;padding-top:8px;padding-bottom:5px}#curfew-pause .nd .cn>span:first-child{min-height:28px}#curfew-pause .nd .cm{margin-top:0}#curfew-pause .br{gap:11px}#curfew-pause .nd+.nd:before{height:10px;top:-12px}#curfew-pause .perk-context{margin:12px 0}#curfew-pause .perk-detail{padding-top:14px}#curfew-pause .perk-emblem{height:65px;font-size:57px}#curfew-pause .menu-footer{margin-top:17px}#curfew-pause .home-moon{width:120px;height:120px}#curfew-pause .home-choice{padding:15px 20px}}
@media(prefers-reduced-motion:reduce){#curfew-pause *{animation:none!important;transition:none!important}}
`;

/** Navigation decorates the real tree, map and weapon meshes; all purchases use Progress. */
export class PauseMenu {
  constructor(hud,{card,wrap,mapWrap,tree,controls}){
    this.hud=hud;this.ctx=hud.ctx;this.page='home';this.selectedNode=NODES[0].id;this.selectedFinish='original';this.weapon='bolt';this.angle=.3;
    card.setAttribute('role','dialog');card.setAttribute('aria-modal','true');card.setAttribute('aria-label','Paused');
    const style=el('style');style.textContent=CSS;card.appendChild(style);
    wrap.replaceChildren();
    const header=el('header','menu-head'),identity=el('div');identity.append(el('div','menu-brand','We Were Promised Morning'));this.title=el('h1','','Paused');identity.append(this.title);header.append(identity);
    this.nav=el('nav','menu-nav');this.nav.setAttribute('aria-label','Pause pages');this.navButtons={};
    for(const [id,title] of [['home','Overview'],['perks','Perks'],['map','Map'],['weapons','Weapons'],['controls','Controls']]){const b=button(title,()=>this.show(id));b.dataset.page=id;this.nav.append(b);this.navButtons[id]=b;}
    header.append(this.nav);wrap.append(header);this.pages={};
    const page=(id,cls)=>{const p=el('section','menu-page '+cls);p.dataset.page=id;p.hidden=true;this.pages[id]=p;wrap.append(p);return p;};
    const home=page('home','pause-home'),intro=el('div');intro.append(el('div','home-moon'));intro.append(el('div','home-name','We Were Promised Morning'));this.homeStatus=el('div','home-status');intro.append(this.homeStatus);home.append(intro);
    const links=el('div','home-choices');
    for(const [id,title,hint,key] of [['resume','Return','Back to the world','Esc'],['perks','Perks','Choose what keeps you alive','Tab'],['map','Map','Places found. Things heard.','M'],['weapons','Weapons','The marks you brought back','']]){const b=button('',()=>id==='resume'?hud._resume():this.show(id),'home-choice'),text=el('span');text.append(el('strong','',title),el('small','',hint));b.append(text,el(key?'kbd':'span','',key||'→'));links.append(b);}home.append(links);
    const perks=page('perks','perks-layout');this.branches=el('div','perk-branches');for(const row of [...tree.querySelectorAll('.br')])this.branches.append(row);tree.append(this.branches);perks.append(tree);
    this.detail=el('aside','perk-detail');this.emblem=el('div','perk-emblem');this.eyebrow=el('div','detail-eyebrow');this.perkName=el('h2');this.description=el('div','perk-description');this.context=el('p','perk-context');const action=el('div','perk-action');this.buy=button('Learn ability',()=>this.purchase(),'primary-action');this.requirement=el('p','detail-requirement');this.requirement.setAttribute('role','status');action.append(this.buy,this.requirement);this.detail.append(this.emblem,this.eyebrow,this.perkName,this.description,this.context,action);perks.append(this.detail);
    const map=page('map','map-page');map.append(mapWrap);this.journal=el('aside','map-journal');map.append(this.journal);
    const weapons=page('weapons','weapons-page');this.finishGrid=el('div','finish-grid');this.finishButtons={};for(const f of FINISHES){const b=button('',()=>{this.selectedFinish=f.id;this.refreshFinishes();this.renderWeapon();},'finish-tile');b.style.setProperty('--finish',HEX(f.colors.base));b.style.setProperty('--accent',HEX(f.colors.accent));b.append(el('strong','',f.name),el('small','',f.location));this.finishGrid.append(b);this.finishButtons[f.id]=b;}weapons.append(this.finishGrid);
    const stage=el('div','finish-stage');this.weaponTabs=el('div','weapon-tabs');this.weaponButtons={};for(const [id,name] of Object.entries(WEAPON_NAMES)){const b=button(name,()=>{this.weapon=id;this.renderWeapon();});this.weaponTabs.append(b);this.weaponButtons[id]=b;}stage.append(this.weaponTabs);this.preview=el('div','weapon-preview');this.preview.setAttribute('aria-label','Weapon finish preview');stage.append(this.preview);this.previewHint=el('p','preview-hint','Drag to rotate · The selected finish applies to every weapon.');stage.append(this.previewHint);
    this.preview.addEventListener('pointerdown',e=>{if(e.button!==0)return;this.preview.setPointerCapture(e.pointerId);this.dragX=e.clientX;});this.preview.addEventListener('pointermove',e=>{if(this.dragX===undefined)return;this.angle+=(e.clientX-this.dragX)*.009;this.dragX=e.clientX;this.renderWeapon();});const release=()=>{this.dragX=undefined;};this.preview.addEventListener('pointerup',release);this.preview.addEventListener('lostpointercapture',release);
    const finishDescription=el('div','finish-description'),finishText=el('div');this.finishName=el('h2');this.finishLore=el('p');finishText.append(this.finishName,this.finishLore);this.equip=button('Equip finish',()=>{if(this.ctx.systems.get('progress')?.equipFinish(this.selectedFinish)){this.refreshFinishes();this.cue();}},'primary-action');finishDescription.append(finishText,this.equip);stage.append(finishDescription);weapons.append(stage);
    const controlPage=page('controls','controls-page');controlPage.append(el('h2','','Controls'),el('p','','Escape returns to the world from any page. Tab opens perks and M opens the map while playing.'),controls);
    const footer=el('footer','menu-footer');footer.append(button('Esc  Return to game',()=>hud._resume()),button('←  Overview',()=>this.show('home')));wrap.append(footer);this.show('home',false);
  }
  cue(){this.ctx.systems.get('progress')?._chimeUI?.('xp_node',1.14,.25);}
  show(id,focus=true){
    this.page=this.pages[id]?id:'home';for(const [key,p] of Object.entries(this.pages))p.hidden=key!==this.page;
    for(const [key,b] of Object.entries(this.navButtons)){if(key===this.page)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}
    this.title.textContent={home:'Paused',perks:'Perks',map:'Map',weapons:'Weapons',controls:'Controls'}[this.page];
    this.hud.pauseEl?.setAttribute('data-page',this.page);this.refresh();
    if(this.page==='map')this.hud._drawMap();if(this.page==='weapons')this.renderWeapon();
    if(focus)this.navButtons[this.page].focus({preventScroll:true});
  }
  refresh(){const p=this.ctx.systems.get('progress'),points=p?.points||0;this.homeStatus.textContent=`Level ${p?.level||1}   ·   ${p?.cash?.()||0} coins\n${points} skill ${points===1?'point':'points'} available`;this.homeStatus.style.whiteSpace='pre-line';this.selectPerk(this.selectedNode);if(this.page==='map')this.refreshJournal();if(this.page==='weapons')this.refreshFinishes();}
  selectPerk(id){
    const n=NODES.find(n=>n.id===id)||NODES[0],b=BRANCHES.find(b=>b.id===n.branch),p=this.ctx.systems.get('progress'),owned=p?.ownedSet?.();this.selectedNode=n.id;
    for(const q of this.hud.nodeEls||[]){q.btn.dataset.selected=String(q.node.id===n.id);q.btn.setAttribute('aria-pressed',String(q.node.id===n.id));q.btn.setAttribute('aria-label',q.node.name+'. '+q.node.line);}
    this.detail.style.setProperty('--accent',HEX(b.tint));this.emblem.textContent=ICONS[b.id];this.eyebrow.textContent=b.name+'  /  '+['I','II','III','IV'][n.tier];this.perkName.textContent=n.name;this.description.textContent=n.line;this.context.textContent=BRANCH_DETAIL[b.id];
    const own=owned?.has(n.id),can=p?.canBuy?.(n.id),pre=NODES.find(q=>q.branch===n.branch&&q.tier===n.tier-1);
    this.buy.disabled=!can;this.buy.textContent=own?'Learned':`Learn · ${n.cost} ${n.cost===1?'point':'points'}`;
    this.requirement.textContent=own?'Yours to keep.':pre&&!owned?.has(pre.id)?'Learn '+pre.name+' first.':!can?`${n.cost} skill ${n.cost===1?'point':'points'} required. Bank experience at a light.`:'Permanently unlock this ability.';
  }
  purchase(){const p=this.ctx.systems.get('progress');if(!p?.buy?.(this.selectedNode))return;this.hud._refreshTree();this.hud._celebrateNode(this.selectedNode);this.selectPerk(this.selectedNode);this.requirement.textContent='Learned.';}
  refreshJournal(){
    const p=this.ctx.systems.get('progress');this.journal.replaceChildren(el('h2','','Places heard about'));
    const rows=p?.rumours?.()||[];if(!rows.length)this.journal.append(el('p','','Talk to people in the Holdfast. What they tell you will be marked here.'));
    for(const r of rows){const state=p.mapStatus(r.id),b=button('',()=>{this.hud.mapCenter={x:r.x,z:r.z};this.hud.mapZoom=2.6;this.hud._drawMap();},'map-pin');b.dataset.state=state;b.append(el('strong','',r.name),el('small','',{rumoured:'?  Heard about · Unvisited',discovered:'◇  Discovered',cleared:'✓  Cleared'}[state]||'Unvisited'));this.journal.append(b);}
  }
  refreshFinishes(){const p=this.ctx.systems.get('progress'),unlocked=p?.unlockedFinishes?.()||['original'],active=p?.activeFinish?.()||'original',f=FINISH_BY_ID[this.selectedFinish]||FINISHES[0];for(const [id,b]of Object.entries(this.finishButtons)){b.dataset.selected=String(id===f.id);b.dataset.locked=String(!unlocked.includes(id));b.dataset.equipped=String(active===id);b.setAttribute('aria-pressed',String(id===f.id));b.setAttribute('aria-label',`${FINISH_BY_ID[id].name}, ${unlocked.includes(id)?active===id?'equipped':'unlocked':'locked'}`);}this.finishName.textContent=f.name;this.finishLore.textContent=f.id==='original'?'The finish you started with.':unlocked.includes(f.id)?`Taken from ${f.boss}. Available on every weapon you own, now and later.`:`Defeat ${f.boss} at ${f.location}. This finish unlocks for every weapon.`;this.equip.disabled=!unlocked.includes(f.id)||active===f.id;this.equip.textContent=active===f.id?'Equipped':unlocked.includes(f.id)?'Equip finish':'Not yet earned';}
  renderWeapon(){
    if(this.page!=='weapons')return;const vm=this.ctx.systems.get('viewmodel'),source=vm?.guns?.[this.weapon]?.group;if(!source)return;
    for(const [id,b]of Object.entries(this.weaponButtons))b.setAttribute('aria-pressed',String(id===this.weapon));
    const owned=this.ctx.systems.get('weapons')?.owned||[];this.previewHint.textContent=(owned.includes(this.weapon)?'':'Weapon not yet owned · ')+'Drag to rotate · Finish applies to every weapon.';
    try{
      if(!this.renderer){
        this.renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});this.renderer.setPixelRatio(Math.min(1.5,devicePixelRatio||1));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.2;this.preview.append(this.renderer.domElement);this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(32,1,.001,100);
        this.scene.add(new THREE.HemisphereLight(0xe5eef6,0x535a68,2.9));
        const key=new THREE.DirectionalLight(0xffeed5,4.5);key.position.set(2,3,3);this.scene.add(key);
        const rim=new THREE.DirectionalLight(0xa9d1ee,3.2);rim.position.set(-2,1,-1);this.scene.add(rim);
        const fill=new THREE.DirectionalLight(0xe0eaf4,1.4);fill.position.set(-1,.5,3);this.scene.add(fill);
        // A broad inspection light reflected by metal, generated once when this page opens.
        // It lights the actual materials; it never replaces them or touches gameplay lighting.
        const canvas=document.createElement('canvas');canvas.width=512;canvas.height=256;const g=canvas.getContext('2d');
        const ambient=g.createLinearGradient(0,0,0,256);ambient.addColorStop(0,'#d9e0e9');ambient.addColorStop(.5,'#78889b');ambient.addColorStop(1,'#222c3b');g.fillStyle=ambient;g.fillRect(0,0,512,256);
        g.fillStyle='#fff6e5';g.fillRect(45,45,120,88);g.fillStyle='#b9d8f0';g.fillRect(360,22,56,152);
        this.previewEnvironment=new THREE.CanvasTexture(canvas);this.previewEnvironment.mapping=THREE.EquirectangularReflectionMapping;this.previewEnvironment.colorSpace=THREE.SRGBColorSpace;this.scene.environment=this.previewEnvironment;
      }
      if(this.previewWeapon!==this.weapon){
        if(this.modelRoot){this.scene.remove(this.modelRoot);for(const m of this.previewMats)m.dispose();}
        this.model=source.clone(true);this.model.visible=true;this.model.position.set(0,0,0);this.model.rotation.set(0,0,0);this.model.scale.setScalar(1);const materials=new Map();this.previewMats=[];
        this.model.traverse(o=>{if(!o.isMesh)return;const clone=m=>{if(materials.has(m))return materials.get(m);const c=m.clone();c.userData={};c.onBeforeCompile=()=>{};c.customProgramCacheKey=()=> 'finish-preview';if(c.isMeshStandardMaterial){const strength=m.userData.finishUniforms?.uFinishStrength?.value??0;finishMaterial(c,strength);const orig=m.userData.finishOriginal;if(orig)c.userData.finishOriginal={...orig};}materials.set(m,c);this.previewMats.push(c);return c;};o.material=Array.isArray(o.material)?o.material.map(clone):clone(o.material);});
        const box=new THREE.Box3().setFromObject(this.model),center=box.getCenter(new THREE.Vector3());this.model.position.sub(center);this.modelRoot=new THREE.Group();this.modelRoot.add(this.model);this.scene.add(this.modelRoot);this.previewWeapon=this.weapon;this.modelSize=box.getSize(new THREE.Vector3()).length();
      }
      for(const m of this.previewMats)setMaterialFinish(m,this.selectedFinish);
      this.modelRoot.rotation.set(-.12,Math.PI/2+this.angle,-.09);const width=Math.max(300,this.preview.clientWidth),height=Math.max(210,this.preview.clientHeight);this.renderer.setSize(width,height,false);this.camera.aspect=width/height;this.camera.updateProjectionMatrix();
      this.modelRoot.updateMatrixWorld(true);const size=new THREE.Box3().setFromObject(this.modelRoot).getSize(new THREE.Vector3()),tan=Math.tan(THREE.MathUtils.degToRad(this.camera.fov*.5));
      const fit=Math.max(size.x/(2*tan*this.camera.aspect*.84),size.y/(2*tan*.76))+size.z*.5;
      this.camera.position.set(0,0,Math.max(this.modelSize*.45,fit));this.camera.lookAt(0,0,0);this.renderer.render(this.scene,this.camera);
    }catch(error){console.error('[weapon preview]',error);this.previewHint.textContent='Weapon preview could not be displayed. Equipping still applies in the world.';}
  }
  dispose(){for(const m of this.previewMats||[])m.dispose();this.previewEnvironment?.dispose();this.renderer?.dispose();this.renderer?.forceContextLoss();}
}
